# example netlify.toml
[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["mdsvex"]

[build.environment]
  NODE_VERSION = "14"
  ## https://github.com/sveltejs/kit/issues/2687

[[headers]]
  ## https://answers.netlify.com/t/content-type-header-not-working-in-netlify-toml/7718
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
    ## Content-Security-Policy = "default-src 'self'; script-src 'nonce-swyx'; img-src *"
